imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

    - { resource: other/fos.yml }
    - { resource: other/be_simple.yml }
    - { resource: other/stof.yml }
    - { resource: other/wsse.yml }
    - { resource: other/genemu.yml }
    - { resource: other/clank.yml }
    - { resource: other/a2lix.yml }
    - { resource: other/lexik.yml }
    - { resource: other/oro.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name:                 BAPID
        handler_id:           %session_handler%
        save_path:            %kernel.root_dir%/cache/sessions
        gc_maxlifetime:       3600
        cookie_httponly:      true
    fragments:
        enabled:              true
        path:                 /_fragment # used for controller action in template
    http_method_override: true
    serializer:
        enabled:              true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller:     "FOS\RestBundle\Controller\ExceptionController::showAction"
    globals:
        bap:
            layout:           ::base.html.twig  # default layout across all Oro bundles
        ws:
            port:             "%websocket_port%"
            host:             "%websocket_host%"

# Assetic Configuration
assetic:
    debug:                    false
    use_controller:           false
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        cssmin:
            file: %kernel.root_dir%/Resources/php/cssmin-v3.0.1.php

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:       "%database_driver%"
                host:         "%database_host%"
                port:         "%database_port%"
                dbname:       "%database_name%"
                user:         "%database_user%"
                password:     "%database_password%"
                charset:      UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping:         true
        class_metadata_factory_name: Oro\Bundle\EntityExtendBundle\Mapping\ExtendClassMetadataFactory
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: Oro\Bundle\UserBundle\Entity\User
        mappings:
            OroDistributionBundle:
                mapping:   false
                is_bundle: true
        metadata_cache_driver:
            type: service
            id: doctrine.metadata.cache

# Swiftmailer Configuration
swiftmailer:
    transport:                "%mailer_transport%"
    host:                     "%mailer_host%"
    port:                     "%mailer_port%"
    encryption:               "%mailer_encryption%"
    username:                 "%mailer_user%"
    password:                 "%mailer_password%"
    spool:                    { type: memory }

# Global Services
services:
    twig.extension.intl:
         class:               Twig_Extensions_Extension_Intl
         tags:
             - { name: twig.extension }

    doctrine.dbal.default.wrapped_connection:
        factory_service:      doctrine.dbal.default_connection
        factory_method:       getWrappedConnection
        class:                PDO

    doctrine.metadata.cache:
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ "doctrine.metadata.cache" ] ]

    session.handler.pdo:
        class:                Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - "@doctrine.dbal.default.wrapped_connection"
            -
              db_table:       oro_session
              db_id_col:      id
