<?php

namespace Acme\Bundle\DemoBundle\Entity;

use Oro\Bundle\FlexibleEntityBundle\Entity\Repository\FlexibleEntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends FlexibleEntityRepository
{
    public function getProducts($maxResults = 0, $offset = 0)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('products')
            ->from('AcmeDemoBundle:Product', 'products');

        if ($maxResults) {
            $query->setMaxResults($maxResults);
        }

        if ($offset) {
            $query->setFirstResult($offset);
        }

        return $query->getQuery()->getResult();
    }
}
